### ISSUE TITLE
Language Braille space

### ISSUE THREAD

**Issue by knghtbrd** [Nalin-x-Linux/ibus-sharada-braille#3]
Hi, I'm not really certain I'm leaving this in the right place, but this appears to be the most current version of what's been packaged in Ubuntu-derivatives as "ibus-braille".

I've found it's very handy as an input method for typing Unicode Braille characters in six or eight dots, with a single exception: The space character. When in Braille language input mode, I would expect the space bar to produce U+2800, not U+0032. That's not something that would be desired in any other language's input method—at least I don't think it would be, and I don't think it can be added without modifying the engine a little.

The reason that it matters is that an ASCII space in most proportional fonts is not wide enough for Braille, which matters when you're inserting it into a document and counting on the fact that a Braille cell is always the same width.

Anyway, figured I'd pose the problem. Apologies if this has a simple solution I'm not aware of after a quick read of the Python source.

**Comment by Nalin-x-Linux** [comment]
please move this issue to latest repository : https://gitlab.com/smc/ibus-braille

**Comment by knghtbrd** [comment]
Done, and more concisely.
